language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.2
- 2.1.1
- 2.1.0
- 2.0.0
- 1.9.3
notifications:
  email: false
  irc:
    template:
    - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
    channels:
    - irc.oftc.net#akerl
